title: "QUBO++ Documentation"
description: "QUBO++ is a C++ library and Python package (PyQBPP) for constructing and solving QUBO/HUBO combinatorial optimization problems."

markdown: kramdown
theme: just-the-docs

highlighter: rouge

url: "https://qubo-plus.github.io"
baseurl: ""

kramdown:
  syntax_highlighter: rouge

safe: false
plugins:
  - jekyll-last-modified-at
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# just-the-docs configuration
logo: "/icon.svg"
color_scheme: light
search_enabled: true
search.button: true

heading_anchors: true

# Navigation structure
nav_external_links:
  - title: "Latest Release"
    url: "https://github.com/qubo-plus/qbpp/releases/latest"
    opens_in_new_tab: true

# Google Analytics
ga_tracking: G-5X2BP69THZ

# Footer
last_edit_timestamp: true
last_edit_time_format: "%Y.%m.%d"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

