source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs"
gem "kramdown-parser-gfm"
gem "jekyll-sass-converter", "~> 2.0"

gem "jekyll-seo-tag"
gem "jekyll-last-modified-at"
gem "jekyll-sitemap"
gem "jekyll-include-cache"
